version: 2
updates:
  # Configuration for NET8 project
  - package-ecosystem: "nuget"
    directory: "/NET8"
    schedule:
      interval: "daily"
      time: "12:00"
      timezone: Asia/Seoul
    open-pull-requests-limit: 10
    target-branch: "main"
    labels:
      - "dependencies"
      - "nuget"
    commit-message:
      prefix: "fix(deps)"
      prefix-development: "chore(deps-dev)"
      include: "scope"
    groups:
      nuget-dependencies:
        patterns:
          - "*"
    allow:
      - dependency-type: "all"

  # Configuration for net481PB project packages.config
  - package-ecosystem: "nuget"
    directory: "/net481PB/packages.config"
    schedule:
      interval: "daily"
      time: "12:00"
      timezone: Asia/Seoul
    open-pull-requests-limit: 10
    target-branch: "main"
    labels:
      - "dependencies"
      - "nuget"
    commit-message:
      prefix: "fix(deps)"
      prefix-development: "chore(deps-dev)"
      include: "scope"
    groups:
      nuget-dependencies:
        patterns:
          - "*"
    allow:
      - dependency-type: "all"

  # Configuration for net481SQL-server project packages.config
  - package-ecosystem: "nuget"
    directory: "/net481SQL-server/packages.config"
    schedule:
      interval: "daily"
      time: "12:00"
      timezone: Asia/Seoul
    open-pull-requests-limit: 10
    target-branch: "main"
    labels:
      - "dependencies"
      - "nuget"
    commit-message:
      prefix: "fix(deps)"
      prefix-development: "chore(deps-dev)"
      include: "scope"
    groups:
      nuget-dependencies:
        patterns:
          - "*"
    allow:
      - dependency-type: "all"

  # Configuration for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "UTC"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"
      include: "scope"
