name: tests for Action

on:
  workflow_dispatch: # Allow manual trigger

jobs:
  test:

    runs-on: windows-2022

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Cache NuGet packages
      uses: actions/cache@v4
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.sln*', '**/*.csproj*') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Restore dependencies
      run: nuget restore -PackagesDirectory ${{ github.workspace }}\packages

    - name: Copy dependencies
      run: |
        Copy-Item -Path ${{ github.workspace }}\packages -Destination ${{ github.workspace }}\net481pb -Recurse
        Copy-Item -Path ${{ github.workspace }}\packages -Destination ${{ github.workspace }}\net481SQL-server -Recurse

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2
    
    - name: Build solution
      run: msbuild "simple-.net-Crypting-For-PowerBuilder.sln" /p:Configuration=Release

    - name: release zip make
      run: |
          Compress-Archive -Path ${{ github.workspace }}\net481PB\bin\Release\*.dll -DestinationPath ${{ github.workspace }}\Release.NET.4.8.PB.zip
          Compress-Archive -Path ${{ github.workspace }}\net481SQL-server\bin\Release\*.dll -DestinationPath ${{ github.workspace }}\Release.NET.4.8.SQL.zip
    
  
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
            D:/a/simple-.net-Crypting-For-PowerBuilder/simple-.net-Crypting-For-PowerBuilder/Release.NET.4.8.PB.zip
            D:/a/simple-.net-Crypting-For-PowerBuilder/simple-.net-Crypting-For-PowerBuilder/Release.NET.4.8.SQL.zip
        tag_name: cd-test-01
